<template>
  <button
    :disabled="disabled"
    :type="type"
    :class="`focus:outline-${variant}-500 bg-${variant}-700 hover:bg-${variant}-600 ${customClass}`"
    class="flex items-center gap-2 px-4 py-2 font-medium text-white transition duration-500 rounded-lg md:mt-5 hover:scale-95 focus:ring-0"
  >
    <svg
      v-if="loading"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="margin: auto; background: none; display: block; shape-rendering: auto;"
      width="20px"
      height="20px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <circle
        cx="50"
        cy="50"
        fill="none"
        stroke="#ffffff"
        stroke-width="10"
        r="35"
        stroke-dasharray="164.93361431346415 56.97787143782138"
      >
        <animateTransform
          attributeName="transform"
          type="rotate"
          repeatCount="indefinite"
          dur="1s"
          values="0 50 50;360 50 50"
          keyTimes="0;1"
        />
      </circle>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: "Button",
  props: {
    type: {
      type: String,
      default: "button",
    },
    customClass: {
      type: String,
      default: "",
    },
    variant: {
      type: String,
      default: "primary",
    },
    block: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    loading: {
      type: Boolean,
      default: false,
    },
  },
};
</script>

<style>
</style>